name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        build_profile: [ linux ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build brainfk
        id: build
        run: >
          BUILD_TYPE=${{matrix.build_type}}
          ${{github.workspace}}/ci/container.sh
          /tmp/cc.fyi.brainfk/ci/build.sh
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build brainfk with coverage
        id: build
        run: >
          BUILD_TYPE=Debug
          BUILD_COVERAGE=1
          ${{github.workspace}}/ci/container.sh
          /tmp/cc.fyi.brainfk/ci/build.sh
      - name: Generate coverage xml
        id: gen-coverage-xml
        run: >
          ci/container.sh
          bash -c "cd /tmp/cc.fyi.brainfk && gcovr --cobertura coverage.xml ."
      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{github.workspace}}/coverage.xml
