name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        build_profile: [ linux ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build brainfk
        id: build
        run: >
          BUILD_TYPE=${{matrix.build_type}}
          ci/container.sh
          /tmp/cc.fyi.brainfk/ci/build.sh
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and test with coverage
        id: build
        run: >
          ci/container.sh /tmp/cc.fyi.brainfk/ci/coverage.sh
      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/coverage.xml'
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
